# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='form/static/images'),
        ),
    ]
